services:
  # Action Server - Internal Service
  - type: web
    name: voyager-actions-server # Make sure this name matches your actions server on Render
    runtime: docker
    repo: https://github.com/Tu5harT/VoyagerAI # Make sure this matches your repo URL
    dockerfilePath: ./Dockerfile.actions
    envVars:
      - key: OPENWEATHER_API_KEY
        fromSecret: true # Assumes you created a secret with this key
        
  # Rasa Server - Public Service with Header Rules
  - type: web
    name: VoyagerAI # This is your main Rasa server
    runtime: docker
    repo: https://github.com/Tu5harT/VoyagerAI # Make sure this matches your repo URL
    dockerfilePath: ./Dockerfile.rasa
    envVars:
      - key: ACTIONS_ENDPOINT_URL
        value: http://voyager-actions-server:10000/webhook
    headers:
      # This is where the header rules go!
      - path: "/*"
        name: "Access-Control-Allow-Origin"
        value: "*"
      - path: "/*"
        name: "Access-Control-Allow-Methods"
        value: "GET, POST, HEAD, OPTIONS"
      - path: "/*"
        name: "Access-Control-Allow-Headers"
        value: "Origin, X-Requested-With, Content-Type, Accept, Authorization"